# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0080c5ce717e17843d2a774153806cea9cc69327b5e0bf06a954189951cd582dc9a8197eb662b680b42b0557f147e062b4d7d63715b732cdc5166b0b37f41c45

test:
  secret_key_base: 98da5d5ca41b41dea70f3257fd201b93c253f3504b721f5eb06292ae6ea1f976cc8db70ab2b8161326b45b6a573272e1853b79cd98ee35cc62843153f01ce193

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
